### ISSUE TITLE
Could not instantiate widget - default folder name convention is wrong

### ISSUE THREAD

**Issue by daquintero** [jupyter-widgets/widget-cookiecutter#108]
Hi,

I think the default `js/lib` naming convention is wrong, and it may have to do with the packaging names between the model instantiation. I say this because I get the error below when building using the default folder name convention and all my files are the same. When I change the `lib` name to `src` on all its instances the widget builds.

My suspicion is that it is in the default `__init__` _jupyter_labextension_paths names.

```
Could not instantiate widget
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
a @ 272.21a3d23ac0c94c50fe81.js:1
Promise.then (async)
l @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e._make_model @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e.new_model @ 272.21a3d23ac0c94c50fe81.js:1
e.handle_comm_open @ 272.21a3d23ac0c94c50fe81.js:1
_handleCommOpen @ 523.8ac49e7b0529950dcdb9.js:1
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleCommOpen (async)
_handleMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleMessage (async)
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
_onWSMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
272.21a3d23ac0c94c50fe81.js:1 Error: Could not create a model.
    at 272.21a3d23ac0c94c50fe81.js:1:2226
    at async _handleCommOpen (523.8ac49e7b0529950dcdb9.js:1:2798)
    at async b._handleCommOpen (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:1039649)
    at async b._handleMessage (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:1041645)
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
Promise.catch (async)
e.handle_comm_open @ 272.21a3d23ac0c94c50fe81.js:1
_handleCommOpen @ 523.8ac49e7b0529950dcdb9.js:1
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleCommOpen (async)
_handleMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleMessage (async)
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
_onWSMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2 Exception opening new comm
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleCommOpen (async)
_handleMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleMessage (async)
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
_onWSMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
523.8ac49e7b0529950dcdb9.js:1 Error: Module gine, semver range ^0.0.4 is not registered as a widget module
    at x.loadClass (523.8ac49e7b0529950dcdb9.js:1:5727)
    at x.<anonymous> (272.21a3d23ac0c94c50fe81.js:1:9500)
    at 272.21a3d23ac0c94c50fe81.js:1:6102
    at Object.next (272.21a3d23ac0c94c50fe81.js:1:6207)
    at 272.21a3d23ac0c94c50fe81.js:1:5143
    at new Promise (<anonymous>)
    at D (272.21a3d23ac0c94c50fe81.js:1:4888)
    at e._make_model (272.21a3d23ac0c94c50fe81.js:1:9379)
    at x.<anonymous> (272.21a3d23ac0c94c50fe81.js:1:9233)
    at 272.21a3d23ac0c94c50fe81.js:1:6102
renderModel @ 523.8ac49e7b0529950dcdb9.js:1
await in renderModel (async)
createRenderedMimetype @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
createOutputItem @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_insertOutput @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
onModelChanged @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
g @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
c @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
e.emit @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_onListChanged @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
g @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
c @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
e.emit @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
push @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_add @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
add @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_onIOPub @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_handleIOPub @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleIOPub (async)
handleMsg @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_handleMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
_onWSMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
523.8ac49e7b0529950dcdb9.js:1 Uncaught (in promise) Error: Module gine, semver range ^0.0.4 is not registered as a widget module
    at x.loadClass (523.8ac49e7b0529950dcdb9.js:1:5727)
    at x.<anonymous> (272.21a3d23ac0c94c50fe81.js:1:9500)
    at 272.21a3d23ac0c94c50fe81.js:1:6102
    at Object.next (272.21a3d23ac0c94c50fe81.js:1:6207)
    at 272.21a3d23ac0c94c50fe81.js:1:5143
    at new Promise (<anonymous>)
    at D (272.21a3d23ac0c94c50fe81.js:1:4888)
    at e._make_model (272.21a3d23ac0c94c50fe81.js:1:9379)
    at x.<anonymous> (272.21a3d23ac0c94c50fe81.js:1:9233)
    at 272.21a3d23ac0c94c50fe81.js:1:6102
loadClass @ 523.8ac49e7b0529950dcdb9.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e._make_model @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e.new_model @ 272.21a3d23ac0c94c50fe81.js:1
e.handle_comm_open @ 272.21a3d23ac0c94c50fe81.js:1
_handleCommOpen @ 523.8ac49e7b0529950dcdb9.js:1
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
e.register_model @ 272.21a3d23ac0c94c50fe81.js:1
register_model @ 523.8ac49e7b0529950dcdb9.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e.new_model @ 272.21a3d23ac0c94c50fe81.js:1
e.handle_comm_open @ 272.21a3d23ac0c94c50fe81.js:1
_handleCommOpen @ 523.8ac49e7b0529950dcdb9.js:1
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleCommOpen (async)
_handleMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleMessage (async)
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
_onWSMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
523.8ac49e7b0529950dcdb9.js:1 Uncaught (in promise) Error: Module gine, semver range ^0.0.4 is not registered as a widget module
    at x.loadClass (523.8ac49e7b0529950dcdb9.js:1:5727)
    at x.<anonymous> (272.21a3d23ac0c94c50fe81.js:1:9500)
    at 272.21a3d23ac0c94c50fe81.js:1:6102
    at Object.next (272.21a3d23ac0c94c50fe81.js:1:6207)
    at 272.21a3d23ac0c94c50fe81.js:1:5143
    at new Promise (<anonymous>)
    at D (272.21a3d23ac0c94c50fe81.js:1:4888)
    at e._make_model (272.21a3d23ac0c94c50fe81.js:1:9379)
    at x.<anonymous> (272.21a3d23ac0c94c50fe81.js:1:9233)
    at 272.21a3d23ac0c94c50fe81.js:1:6102
loadClass @ 523.8ac49e7b0529950dcdb9.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e._make_model @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e.new_model @ 272.21a3d23ac0c94c50fe81.js:1
e.handle_comm_open @ 272.21a3d23ac0c94c50fe81.js:1
_handleCommOpen @ 523.8ac49e7b0529950dcdb9.js:1
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
register_model @ 523.8ac49e7b0529950dcdb9.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
(anonymous) @ 272.21a3d23ac0c94c50fe81.js:1
D @ 272.21a3d23ac0c94c50fe81.js:1
e.new_model @ 272.21a3d23ac0c94c50fe81.js:1
e.handle_comm_open @ 272.21a3d23ac0c94c50fe81.js:1
_handleCommOpen @ 523.8ac49e7b0529950dcdb9.js:1
_handleCommOpen @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleCommOpen (async)
_handleMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _handleMessage (async)
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
Promise.then (async)
_onWSMessage @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2 TypeError: Cannot read properties of undefined (reading 'sendSaved')
    at pe.on_save_state (adapter.ts:308:20)
    at g (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:1607793)
    at Object.c [as emit] (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:1607453)
    at e.emit (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:1605542)
    at h._save (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:515868)
    at async h.save (jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2:510720)
e.exceptionHandler @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
g @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
c @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
e.emit @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
_save @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in _save (async)
save @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
await in save (async)
_save @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
(anonymous) @ jlab_core.4d5114e25256eeddf4e4.js?v=4d5114e25256eeddf4e4:2
```

**Comment by daquintero** [comment]
It was a dependency problem on errors above on installing ipyevents and ipytree
